dist: jammy
language: java
sudo: required
jdk:
  - openjdk17
  - openjdk18
  - openjdk19
  - openjdk20
  - openjdk21
  - openjdk22
before_script:
  - wget "https://github.com/nats-io/nats-server/releases/download/$nats_server_version/nats-server-$nats_server_version-linux-amd64.zip"
    -O tmp.zip
  - unzip tmp.zip
  - mv nats-server-$nats_server_version-linux-amd64 nats-server
install: mvn install -DskipTests -Dgpg.skip
env:
  global:
    - nats_server_version=v2.0.2
    - nats_server_path=$TRAVIS_BUILD_DIR/nats-server/nats-server
