spring:
  cloud:
    stream:
      function:
        bindings:
          transform-in-0: input
          transform-out-0: output
      bindings:
        input:
          destination: dataIn
          binder: nats
        output:
          destination: dataOut
          binder: nats
nats:
  spring:
    server: nats://localhost:4222
